name: Ruby

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Checkout gh-pages with latest changes
      run: |
        git config --global user.email "team@cucumber.io"
        git config --global user.name "GitHub Action"
        git checkout master
        git pull
        git checkout gh-pages
        git rebase master
        cd ruby
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
        git status
        git add index.html
        git commit -m "Building latest asciidoc"
        git push --force
