name: Build AsciiDoc at https://cucumber-school.github.com/bdd-fundamentals

on:
  push:
    branches:
      - master
      - ci

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Build asciidoc
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        shots=1 bundle exec rake
    - name: Create GH Pages
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: public
